---
- community.general.modprobe:
    name: br_netfilter
    state: present

- ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes

- ansible.posix.sysctl:
    name: "{{ item }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- import_tasks: kubeadm_debian.yml
  tags:
    - debian
  when: ansible_distribution_file_variety | lower == 'debian'

- import_tasks: kubeadm_redhat.yml
  tags:
    - redhat
  when: ansible_distribution_file_variety | lower == 'redhat'
