---
- import_tasks: debian.yml
  become: yes
  tags:
    - debian
  when: ansible_distribution_file_variety | lower == 'debian'

- import_tasks: redhat.yml
  become: yes
  tags:
    - redhat
  when: ansible_distribution_file_variety | lower == 'redhat'
